pipeline {
    agent any
     environment {
        BUCKET_NAME = "jenkins-udemy-0"
    }

    stages {
        stage('AWS') {
            agent {
                docker {
                    image 'amazon/aws-cli'
                    args '--entrypoint=""'
                }
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'my-aws', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
                    // some block
                    sh''' 
                    aws --version
                    echo "Uploading website files to S3..."
                    aws s3 sync FirstWebsite/ s3://$BUCKET_NAME --delete
                    echo "Upload completed successfully"
                    aws s3 ls
                
                     '''
                }
               
            }
        }
    }
}
